### ISSUE TITLE
MKSLaserTool_setupV2.0.4.exe issue PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by tca72** [makerbase-mks/MKS-DLC32#510]
On windows 10 , after installing MKSLaserTool_setupV2.0.4.exe on my computer, when I am trying to execute it I've got the following error. ( installed as administrator)
![Uploading Error.JPG…]()

Traceback (most recent call last):
  File "ncChangeTool.py", line 3184, in <module>
  File "ncChangeTool.py", line 3054, in __init__
  File "ncChangeTool.py", line 3165, in getLanguage
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\MKSLaserTool\\\\resources\\l.l'

**Comment by tca72** [comment]
Solved by installing on C:\MKSLaserTool instead on C:\Program Files (x86)\MKSLaserTool

**Comment by s3liha** [comment]
good
